### PR TITLE
fixed #12 Added 's color data to colors.js

### LINKED ISSUE #12: Issue on level 8 "soil"
Issue on level 8 "soil". Seems level 8 "soil" 's color data not exist in file `colors.js`. (O.O;

### PR DESCRIPTION
**Pull request by Tx-Charlie**
fixed #12 

(Thx for ch3pjw :D)

### CODE REVIEW

**Review by ch3pjw — APPROVED** [review]
Looks ok to me - sorry for the slow review, this slipped off my radar!

**Comment by ch3pjw** [comment]
@halfsail - are you happy to merge this or would you like me to do it? I can take over maintenance if you don't have the time to look at this any more?

**Comment by Tx-Charlie** [comment]
Thx xD

**Comment by halfsail** [comment]
Yes please. I'm more than happy to continuing working on the design. But I
don't have hardware to work on the app.

**Comment by ch3pjw** [comment]
What I'm not sure about is how the release process works for new versions... I only ever updated the code!

**Pull request merged**
